"""Runtime adapters for coding-agent harnesses beyond Claude/Copilot.

CoderMind's core CLI predates Agent Skills and keeps most provisioning logic in
``cmind_cli.__init__``.  This module layers newer harnesses on top without
forking the RPG/encoder pipeline:

* Codex CLI: project Agent Skills + project ``.codex/config.toml`` MCP config.
* Pi coding agent: project Agent Skills + a tiny MCP bridge extension.
* oh-my-pi (OMP): native project skills + native ``.omp/mcp.json`` config.

``install()`` mutates the existing CLI registries and wraps the two provisioning
functions that are intentionally agent-specific.  Keeping this compatibility
layer separate makes it possible to move the same definitions into a first-class
AgentAdapter API later without changing the generated workspace contract.
"""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path
from types import ModuleType
from typing import Callable


_ADAPTER_AGENTS = {
    "codex": {
        "name": "OpenAI Codex CLI",
        "folder": ".codex/",
        "install_url": "https://developers.openai.com/codex/cli",
        "requires_cli": True,
        "cli_cmd": "codex exec",
        "skill_root": (".agents", "skills"),
        "skill_invocation": "codex",
    },
    "pi": {
        "name": "Pi coding agent",
        "folder": ".pi/",
        "install_url": "https://github.com/badlogic/pi-mono/tree/main/packages/coding-agent",
        "requires_cli": True,
        "cli_cmd": "pi -p",
        "skill_root": (".agents", "skills"),
        "skill_invocation": "pi",
    },
    "omp": {
        "name": "oh-my-pi",
        "folder": ".omp/",
        "install_url": "https://github.com/can1357/oh-my-pi",
        "requires_cli": True,
        "cli_cmd": "omp -p",
        "skill_root": (".omp", "skills"),
        "skill_invocation": "pi",
    },
}

_GITIGNORE_RULES = {
    "codex": """\
# CoderMind Agent Skills for Codex (regenerated by cmind)
.agents/skills/cmind-*/
""",
    "pi": """\
# CoderMind Agent Skills and MCP bridge for Pi (regenerated by cmind)
.agents/skills/cmind-*/
.pi/mcp.json
.pi/extensions/cmind-mcp.ts
""",
    "omp": """\
# CoderMind native skills/MCP config for oh-my-pi (regenerated by cmind)
.omp/skills/cmind-*/
.omp/mcp.json
""",
}

_FRONTMATTER_RE = re.compile(r"\A---\s*\n(?P<meta>.*?)\n---\s*\n?", re.DOTALL)
_CMIND_COMMAND_RE = re.compile(r"/cmind\.([A-Za-z0-9_]+)")


def _skill_slug(command_stem: str) -> str:
    return "cmind-" + command_stem.replace("_", "-")


def _extract_description(meta: str, fallback: str) -> str:
    for line in meta.splitlines():
        if line.startswith("description:"):
            value = line.split(":", 1)[1].strip()
            if value:
                return value
    return fallback


def _render_skill(source: str, stem: str, invocation: str) -> str:
    """Convert a legacy ``/cmind.*`` command template to Agent Skills format."""
    match = _FRONTMATTER_RE.match(source)
    if match:
        body = source[match.end() :]
        description = _extract_description(
            match.group("meta"), f"Run the CoderMind {stem} workflow"
        )
    else:
        body = source
        description = f"Run the CoderMind {stem} workflow"

    slug = _skill_slug(stem)

    def replace_command(command_match: re.Match[str]) -> str:
        target = _skill_slug(command_match.group(1))
        if invocation == "codex":
            return f"${target}"
        return f"/skill:{target}"

    body = _CMIND_COMMAND_RE.sub(replace_command, body)
    body = body.replace(
        "$ARGUMENTS",
        "Use the user's current request and any explicit skill invocation arguments.",
    )

    return (
        "---\n"
        f"name: {slug}\n"
        f"description: {description}\n"
        "---\n\n"
        f"{body.lstrip()}"
    )


def _materialise_skills(
    ai_assistant: str, src_commands_dir: Path, project_path: Path
) -> None:
    spec = _ADAPTER_AGENTS[ai_assistant]
    dest = project_path.joinpath(*spec["skill_root"])
    dest.mkdir(parents=True, exist_ok=True)

    for src in src_commands_dir.glob("*.md"):
        skill_dir = dest / _skill_slug(src.stem)
        skill_dir.mkdir(parents=True, exist_ok=True)
        rendered = _render_skill(
            src.read_text(encoding="utf-8"),
            src.stem,
            spec["skill_invocation"],
        )
        (skill_dir / "SKILL.md").write_text(rendered, encoding="utf-8")


def _load_json_object(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        raise ValueError(f"Refusing to overwrite malformed JSON: {path}")
    if not isinstance(data, dict):
        raise ValueError(f"Expected a JSON object in {path}")
    return data


def _write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _configure_codex_mcp(project_path: Path) -> None:
    config_path = project_path / ".codex" / "config.toml"
    config_path.parent.mkdir(parents=True, exist_ok=True)

    current = ""
    parsed: dict = {}
    if config_path.exists():
        current = config_path.read_text(encoding="utf-8")
        try:
            parsed = tomllib.loads(current)
        except tomllib.TOMLDecodeError as exc:
            raise ValueError(
                f"Refusing to overwrite malformed TOML: {config_path}: {exc}"
            ) from exc

    servers = parsed.get("mcp_servers", {})
    if servers and not isinstance(servers, dict):
        raise ValueError(f"Expected mcp_servers to be a table in {config_path}")
    existing = servers.get("rpg_tools") if isinstance(servers, dict) else None
    if existing is not None:
        # Respect a user-customized server.  An in-sync CoderMind entry is
        # already complete; anything else is deliberately left untouched.
        return

    block = (
        "[mcp_servers.rpg_tools]\n"
        'command = "cmind-mcp"\n'
        "args = []\n"
    )
    prefix = current
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    if prefix and not prefix.endswith("\n\n"):
        prefix += "\n"
    config_path.write_text(prefix + block, encoding="utf-8")


def _configure_omp_mcp(project_path: Path) -> None:
    path = project_path / ".omp" / "mcp.json"
    data = _load_json_object(path)
    servers = data.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        raise ValueError(f"Expected mcpServers to be an object in {path}")
    servers.setdefault(
        "rpg-tools",
        {
            "type": "stdio",
            "command": "cmind-mcp",
            "args": [],
        },
    )
    _write_json(path, data)


_PI_MCP_EXTENSION = r'''import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { createInterface } from "node:readline";

type JsonObject = Record<string, any>;

type Pending = {
  resolve: (value: any) => void;
  reject: (reason?: any) => void;
};

class McpStdioClient {
  private child: ChildProcessWithoutNullStreams | null = null;
  private nextId = 1;
  private pending = new Map<number, Pending>();

  async start(): Promise<void> {
    if (this.child) return;
    const child = spawn("cmind-mcp", [], {
      stdio: ["pipe", "pipe", "pipe"],
      env: process.env,
    });
    this.child = child;

    const lines = createInterface({ input: child.stdout });
    lines.on("line", (line) => {
      let message: JsonObject;
      try {
        message = JSON.parse(line);
      } catch {
        return;
      }
      if (typeof message.id !== "number") return;
      const waiter = this.pending.get(message.id);
      if (!waiter) return;
      this.pending.delete(message.id);
      if (message.error) waiter.reject(new Error(message.error.message ?? "MCP error"));
      else waiter.resolve(message.result);
    });

    const failAll = (error: Error) => {
      for (const waiter of this.pending.values()) waiter.reject(error);
      this.pending.clear();
      this.child = null;
    };
    child.on("error", (error) => failAll(error));
    child.on("exit", (code) => {
      failAll(new Error(`cmind-mcp exited with code ${code ?? "unknown"}`));
    });

    child.stderr.on("data", () => {
      // Drain diagnostics so a verbose server cannot fill the stderr pipe.
    });

    await this.request("initialize", {
      protocolVersion: "2025-06-18",
      capabilities: {},
      clientInfo: { name: "codermind-pi", version: "0.1" },
    });
    this.notify("notifications/initialized", {});
  }

  private write(message: JsonObject): void {
    if (!this.child) throw new Error("cmind-mcp is not running");
    this.child.stdin.write(JSON.stringify(message) + "\n");
  }

  notify(method: string, params: JsonObject): void {
    this.write({ jsonrpc: "2.0", method, params });
  }

  request(method: string, params: JsonObject = {}): Promise<any> {
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      this.pending.set(id, { resolve, reject });
      this.write({ jsonrpc: "2.0", id, method, params });
    });
  }

  stop(): void {
    this.child?.kill();
    this.child = null;
  }
}

export default async function (pi: ExtensionAPI) {
  const client = new McpStdioClient();
  await client.start();
  const listed = await client.request("tools/list");

  for (const tool of listed.tools ?? []) {
    pi.registerTool({
      name: `mcp_rpg_tools_${tool.name}`,
      label: `CoderMind: ${tool.name}`,
      description: tool.description ?? `CoderMind RPG tool ${tool.name}`,
      parameters: Type.Unsafe(tool.inputSchema ?? { type: "object", properties: {} }),
      async execute(_toolCallId, params) {
        const result = await client.request("tools/call", {
          name: tool.name,
          arguments: params ?? {},
        });
        return {
          content: result.content ?? [{ type: "text", text: JSON.stringify(result) }],
          details: result,
          isError: result.isError ?? false,
        };
      },
    } as any);
  }

  pi.on("session_shutdown", async () => {
    client.stop();
  });
}
'''


def _configure_pi_mcp(project_path: Path) -> None:
    # Keep a standard MCP declaration alongside the bridge so the workspace is
    # self-describing and can migrate to native Pi MCP if/when it lands.
    path = project_path / ".pi" / "mcp.json"
    data = _load_json_object(path)
    servers = data.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        raise ValueError(f"Expected mcpServers to be an object in {path}")
    servers.setdefault("rpg-tools", {"command": "cmind-mcp", "args": []})
    _write_json(path, data)

    extension = project_path / ".pi" / "extensions" / "cmind-mcp.ts"
    extension.parent.mkdir(parents=True, exist_ok=True)
    extension.write_text(_PI_MCP_EXTENSION, encoding="utf-8")


def _configure_mcp(project_path: Path, ai_assistant: str) -> None:
    if ai_assistant == "codex":
        _configure_codex_mcp(project_path)
    elif ai_assistant == "pi":
        _configure_pi_mcp(project_path)
    elif ai_assistant == "omp":
        _configure_omp_mcp(project_path)
    else:  # pragma: no cover - guarded by caller
        raise ValueError(f"Unsupported adapter: {ai_assistant}")


def install(core: ModuleType) -> None:
    """Install the adapter layer into the legacy ``cmind_cli`` module."""
    if getattr(core, "_MULTI_AGENT_ADAPTERS_INSTALLED", False):
        return

    for key, spec in _ADAPTER_AGENTS.items():
        core.AGENT_CONFIG[key] = {
            "name": spec["name"],
            "folder": spec["folder"],
            "install_url": spec["install_url"],
            "requires_cli": spec["requires_cli"],
        }
        core._AI_TO_CLI_CMD[key] = spec["cli_cmd"]
        core._GITIGNORE_CMIND_AI[key] = _GITIGNORE_RULES[key]

    original_materialise: Callable = core._materialise_commands_for_agent
    original_mcp: Callable = core._generate_mcp_config

    def materialise_commands_for_agent(
        ai_assistant: str, src_commands_dir: Path, project_path: Path
    ) -> None:
        if ai_assistant in _ADAPTER_AGENTS:
            _materialise_skills(ai_assistant, src_commands_dir, project_path)
            return
        original_materialise(ai_assistant, src_commands_dir, project_path)

    def generate_mcp_config(
        project_path: Path, selected_ai: str, tracker=None
    ) -> None:
        if selected_ai not in _ADAPTER_AGENTS:
            original_mcp(project_path, selected_ai, tracker=tracker)
            return

        try:
            _configure_mcp(project_path.resolve(), selected_ai)
            if tracker:
                tracker.complete("mcp", f"configured for {selected_ai}")
        except Exception as exc:
            if tracker:
                tracker.error("mcp", f"failed: {exc}")
            else:
                core.console.print(
                    f"[yellow]Warning: Could not generate MCP config: {exc}[/yellow]"
                )

    core._materialise_commands_for_agent = materialise_commands_for_agent
    core._generate_mcp_config = generate_mcp_config
    core._MULTI_AGENT_ADAPTERS_INSTALLED = True
