"""Runtime adapters for coding-agent harnesses beyond Claude/Copilot.

The adapters generated here are *host driven*: Codex, Pi, or OMP remains the
only model-bearing agent.  CoderMind contributes Agent Skills, RPG MCP tools,
and deterministic Python pipelines.  When a legacy pipeline reaches an
``LLMClient`` call, the ``cmind host`` bridge surfaces that prompt back to the
current host agent instead of launching ``codex exec``, ``pi -p``, or another
nested coding agent.
"""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path
from types import ModuleType
from typing import Callable


_ADAPTER_AGENTS = {
    "codex": {
        "name": "OpenAI Codex (App / CLI / IDE)",
        "folder": ".codex/",
        "install_url": "https://developers.openai.com/codex/",
        # Codex App can use project skills/MCP without a local `codex` CLI.
        "requires_cli": False,
        "legacy_cli_cmd": "codex exec",
        "skill_root": (".agents", "skills"),
        "skill_invocation": "codex",
    },
    "pi": {
        "name": "Pi coding agent",
        "folder": ".pi/",
        "install_url": "https://github.com/badlogic/pi-mono/tree/main/packages/coding-agent",
        # CoderMind never shells back into Pi; the running Pi session is host.
        "requires_cli": False,
        "legacy_cli_cmd": "pi -p",
        "skill_root": (".agents", "skills"),
        "skill_invocation": "pi",
    },
    "omp": {
        "name": "oh-my-pi",
        "folder": ".omp/",
        "install_url": "https://github.com/can1357/oh-my-pi",
        "requires_cli": False,
        "legacy_cli_cmd": "omp -p",
        "skill_root": (".omp", "skills"),
        "skill_invocation": "pi",
    },
}

_GITIGNORE_RULES = {
    "codex": """\
# CoderMind Agent Skills / host-run state for Codex (regenerated by cmind)
.agents/skills/cmind-*/
.agents/cmind/
.cmind/host-runs/
""",
    "pi": """\
# CoderMind Agent Skills, MCP bridge and host-run state for Pi
.agents/skills/cmind-*/
.agents/cmind/
.pi/mcp.json
.pi/extensions/cmind-mcp.ts
.cmind/host-runs/
""",
    "omp": """\
# CoderMind native skills/MCP config and host-run state for oh-my-pi
.omp/skills/cmind-*/
.omp/cmind/
.omp/mcp.json
.cmind/host-runs/
""",
}

_FRONTMATTER_RE = re.compile(r"\A---\s*\n(?P<meta>.*?)\n---\s*\n?", re.DOTALL)
_CMIND_COMMAND_RE = re.compile(r"/cmind\.([A-Za-z0-9_]+)")

_HOST_PROTOCOL_REFERENCE = """\
# CoderMind host-model execution protocol

This workspace uses **host-driven CoderMind**. The current coding-agent session
is the only model. CoderMind must not launch another AI CLI.

Whenever this workflow shows a command beginning with `cmind host start`:

1. Run it and remember the returned `run_id`.
2. Run `cmind host next <run_id>`.
3. If the status is `input_required`, reason over the returned `prompt` yourself
   in this current session. Submit your complete response on stdin:

   ```bash
   cat <<'CMIND_RESPONSE' | cmind host reply <run_id> <request_id>
   <your response to the CoderMind prompt>
   CMIND_RESPONSE
   ```

4. Repeat `cmind host next <run_id>` and reply to every `input_required` request.
5. Stop when the status is `completed` or `failed`. Use the returned `stdout`
   as the script result and inspect `stderr` on failure.

Do not replace this protocol with `codex exec`, `pi -p`, `omp -p`, or another
nested model invocation.

"""

_HOST_PROTOCOL_POINTER = """\
## Host-model execution

Before running a command beginning with `cmind host start`, read and follow the
[shared host-model protocol](../../cmind/host-protocol.md). It is the
authoritative procedure for completing host-driven model requests.

"""


def _skill_slug(command_stem: str) -> str:
    return "cmind-" + command_stem.replace("_", "-")


def _extract_description(meta: str, fallback: str) -> str:
    for line in meta.splitlines():
        if line.startswith("description:"):
            value = line.split(":", 1)[1].strip()
            if value:
                return value
    return fallback


def _render_skill(source: str, stem: str, invocation: str) -> str:
    """Convert a legacy ``/cmind.*`` template to a host-driven Agent Skill."""
    match = _FRONTMATTER_RE.match(source)
    if match:
        body = source[match.end() :]
        description = _extract_description(
            match.group("meta"), f"Run the CoderMind {stem} workflow"
        )
    else:
        body = source
        description = f"Run the CoderMind {stem} workflow"

    slug = _skill_slug(stem)

    def replace_command(command_match: re.Match[str]) -> str:
        target = _skill_slug(command_match.group(1))
        if invocation == "codex":
            return f"${target}"
        return f"/skill:{target}"

    body = _CMIND_COMMAND_RE.sub(replace_command, body)
    body = body.replace(
        "$ARGUMENTS",
        "Use the user's current request and any explicit skill invocation arguments.",
    )
    # Existing workflow templates invoke packaged scripts directly.  In a
    # host-driven adapter every script goes through the bridge, so any nested
    # LLMClient call is surfaced back to this same agent session.
    body = body.replace("cmind script ", "cmind host start ")

    return (
        "---\n"
        f"name: {slug}\n"
        f"description: {description}\n"
        "---\n\n"
        f"{_HOST_PROTOCOL_POINTER}"
        f"{body.lstrip()}"
    )


def _materialise_skills(
    ai_assistant: str, src_commands_dir: Path, project_path: Path
) -> None:
    spec = _ADAPTER_AGENTS[ai_assistant]
    dest = project_path.joinpath(*spec["skill_root"])
    dest.mkdir(parents=True, exist_ok=True)
    shared_dir = dest.parent / "cmind"
    shared_dir.mkdir(parents=True, exist_ok=True)
    (shared_dir / "host-protocol.md").write_text(
        _HOST_PROTOCOL_REFERENCE,
        encoding="utf-8",
    )

    for src in src_commands_dir.glob("*.md"):
        skill_dir = dest / _skill_slug(src.stem)
        skill_dir.mkdir(parents=True, exist_ok=True)
        rendered = _render_skill(
            src.read_text(encoding="utf-8"),
            src.stem,
            spec["skill_invocation"],
        )
        (skill_dir / "SKILL.md").write_text(rendered, encoding="utf-8")


def _load_json_object(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        raise ValueError(f"Refusing to overwrite malformed JSON: {path}")
    if not isinstance(data, dict):
        raise ValueError(f"Expected a JSON object in {path}")
    return data


def _write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _configure_codex_mcp(project_path: Path) -> None:
    config_path = project_path / ".codex" / "config.toml"
    config_path.parent.mkdir(parents=True, exist_ok=True)

    current = ""
    parsed: dict = {}
    if config_path.exists():
        current = config_path.read_text(encoding="utf-8")
        try:
            parsed = tomllib.loads(current)
        except tomllib.TOMLDecodeError as exc:
            raise ValueError(
                f"Refusing to overwrite malformed TOML: {config_path}: {exc}"
            ) from exc

    servers = parsed.get("mcp_servers", {})
    if servers and not isinstance(servers, dict):
        raise ValueError(f"Expected mcp_servers to be a table in {config_path}")
    existing = servers.get("rpg_tools") if isinstance(servers, dict) else None
    if existing is not None:
        # Respect a user-customized server.
        return

    block = (
        "[mcp_servers.rpg_tools]\n"
        'command = "cmind-mcp"\n'
        "args = []\n"
    )
    prefix = current
    if prefix and not prefix.endswith("\n"):
        prefix += "\n"
    if prefix and not prefix.endswith("\n\n"):
        prefix += "\n"
    config_path.write_text(prefix + block, encoding="utf-8")


def _configure_omp_mcp(project_path: Path) -> None:
    path = project_path / ".omp" / "mcp.json"
    data = _load_json_object(path)
    servers = data.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        raise ValueError(f"Expected mcpServers to be an object in {path}")
    servers.setdefault(
        "rpg-tools",
        {
            "type": "stdio",
            "command": "cmind-mcp",
            "args": [],
        },
    )
    _write_json(path, data)


_PI_MCP_EXTENSION = r'''import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { createInterface } from "node:readline";

type JsonObject = Record<string, any>;

type Pending = {
  resolve: (value: any) => void;
  reject: (reason?: any) => void;
};

class McpStdioClient {
  private child: ChildProcessWithoutNullStreams | null = null;
  private nextId = 1;
  private pending = new Map<number, Pending>();

  async start(): Promise<void> {
    if (this.child) return;
    const child = spawn("cmind-mcp", [], {
      stdio: ["pipe", "pipe", "pipe"],
      env: process.env,
    });
    this.child = child;

    const lines = createInterface({ input: child.stdout });
    lines.on("line", (line) => {
      let message: JsonObject;
      try {
        message = JSON.parse(line);
      } catch {
        return;
      }
      if (typeof message.id !== "number") return;
      const waiter = this.pending.get(message.id);
      if (!waiter) return;
      this.pending.delete(message.id);
      if (message.error) waiter.reject(new Error(message.error.message ?? "MCP error"));
      else waiter.resolve(message.result);
    });

    const failAll = (error: Error) => {
      for (const waiter of this.pending.values()) waiter.reject(error);
      this.pending.clear();
      this.child = null;
    };
    child.on("error", (error) => failAll(error));
    child.on("exit", (code) => {
      failAll(new Error(`cmind-mcp exited with code ${code ?? "unknown"}`));
    });

    child.stderr.on("data", () => {
      // Drain diagnostics so a verbose server cannot fill the stderr pipe.
    });

    await this.request("initialize", {
      protocolVersion: "2025-06-18",
      capabilities: {},
      clientInfo: { name: "codermind-pi", version: "0.1" },
    });
    this.notify("notifications/initialized", {});
  }

  private write(message: JsonObject): void {
    if (!this.child) throw new Error("cmind-mcp is not running");
    this.child.stdin.write(JSON.stringify(message) + "\n");
  }

  notify(method: string, params: JsonObject): void {
    this.write({ jsonrpc: "2.0", method, params });
  }

  request(method: string, params: JsonObject = {}): Promise<any> {
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      this.pending.set(id, { resolve, reject });
      this.write({ jsonrpc: "2.0", id, method, params });
    });
  }

  stop(): void {
    this.child?.kill();
    this.child = null;
  }
}

export default async function (pi: ExtensionAPI) {
  const client = new McpStdioClient();
  await client.start();
  const listed = await client.request("tools/list");

  for (const tool of listed.tools ?? []) {
    pi.registerTool({
      name: `mcp_rpg_tools_${tool.name}`,
      label: `CoderMind: ${tool.name}`,
      description: tool.description ?? `CoderMind RPG tool ${tool.name}`,
      parameters: Type.Unsafe(tool.inputSchema ?? { type: "object", properties: {} }),
      async execute(_toolCallId, params) {
        const result = await client.request("tools/call", {
          name: tool.name,
          arguments: params ?? {},
        });
        return {
          content: result.content ?? [{ type: "text", text: JSON.stringify(result) }],
          details: result,
          isError: result.isError ?? false,
        };
      },
    } as any);
  }

  pi.on("session_shutdown", async () => {
    client.stop();
  });
}
'''


def _configure_pi_mcp(project_path: Path) -> None:
    # Keep a standard declaration alongside the bridge so the workspace is
    # self-describing and can migrate to native Pi MCP if/when it lands.
    path = project_path / ".pi" / "mcp.json"
    data = _load_json_object(path)
    servers = data.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        raise ValueError(f"Expected mcpServers to be an object in {path}")
    servers.setdefault("rpg-tools", {"command": "cmind-mcp", "args": []})
    _write_json(path, data)

    extension = project_path / ".pi" / "extensions" / "cmind-mcp.ts"
    extension.parent.mkdir(parents=True, exist_ok=True)
    extension.write_text(_PI_MCP_EXTENSION, encoding="utf-8")


def _configure_mcp(project_path: Path, ai_assistant: str) -> None:
    if ai_assistant == "codex":
        _configure_codex_mcp(project_path)
    elif ai_assistant == "pi":
        _configure_pi_mcp(project_path)
    elif ai_assistant == "omp":
        _configure_omp_mcp(project_path)
    else:  # pragma: no cover - guarded by caller
        raise ValueError(f"Unsupported adapter: {ai_assistant}")


def _write_host_workspace_config(core: ModuleType, project_path: Path, agent: str) -> None:
    """Write/migrate ``.cmind/config.toml`` for host-model execution.

    A previous revision of this adapter scaffolded ``ai_cli_cmd = \"codex exec\"``
    (and equivalent Pi/OMP commands).  We migrate only that exact generated
    value; any custom command remains untouched.
    """
    cfg_path = project_path / core._CONFIG_RELPATH
    spec = _ADAPTER_AGENTS[agent]
    legacy_line = f'ai_cli_cmd = "{spec["legacy_cli_cmd"]}"'
    host_block = f'execution_mode = "host"\nagent = "{agent}"'

    if cfg_path.exists():
        current = cfg_path.read_text(encoding="utf-8")
        if 'execution_mode = "host"' in current:
            return
        if legacy_line in current:
            cfg_path.write_text(current.replace(legacy_line, host_block, 1), encoding="utf-8")
        # Preserve user-customized config rather than silently changing it.
        return

    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    cfg_path.write_text(
        "# CoderMind workspace configuration\n"
        "# Host-driven adapters keep all model reasoning in the current agent session.\n"
        "\n"
        "[cmind]\n"
        f'{host_block}\n',
        encoding="utf-8",
    )


def install(core: ModuleType) -> None:
    """Install the host-driven adapter layer into the legacy ``cmind_cli`` module."""
    if getattr(core, "_MULTI_AGENT_ADAPTERS_INSTALLED", False):
        return

    for key, spec in _ADAPTER_AGENTS.items():
        core.AGENT_CONFIG[key] = {
            "name": spec["name"],
            "folder": spec["folder"],
            "install_url": spec["install_url"],
            "requires_cli": spec["requires_cli"],
        }
        # Deliberately do NOT add these harnesses to _AI_TO_CLI_CMD. Their
        # current session is the model host; CoderMind must not shell back into
        # the same (or another) coding agent.
        core._GITIGNORE_CMIND_AI[key] = _GITIGNORE_RULES[key]

    original_materialise: Callable = core._materialise_commands_for_agent
    original_mcp: Callable = core._generate_mcp_config
    original_workspace_config: Callable = core._write_workspace_config

    def materialise_commands_for_agent(
        ai_assistant: str, src_commands_dir: Path, project_path: Path
    ) -> None:
        if ai_assistant in _ADAPTER_AGENTS:
            _materialise_skills(ai_assistant, src_commands_dir, project_path)
            return
        original_materialise(ai_assistant, src_commands_dir, project_path)

    def generate_mcp_config(
        project_path: Path, selected_ai: str, tracker=None
    ) -> None:
        if selected_ai not in _ADAPTER_AGENTS:
            original_mcp(project_path, selected_ai, tracker=tracker)
            return

        try:
            _configure_mcp(project_path.resolve(), selected_ai)
            if tracker:
                tracker.complete("mcp", f"configured for {selected_ai}")
        except Exception as exc:
            if tracker:
                tracker.error("mcp", f"failed: {exc}")
            else:
                core.console.print(
                    f"[yellow]Warning: Could not generate MCP config: {exc}[/yellow]"
                )

    def write_workspace_config(project_path: Path, selected_ai: str) -> None:
        if selected_ai in _ADAPTER_AGENTS:
            _write_host_workspace_config(core, project_path, selected_ai)
            return
        original_workspace_config(project_path, selected_ai)

    core._materialise_commands_for_agent = materialise_commands_for_agent
    core._generate_mcp_config = generate_mcp_config
    core._write_workspace_config = write_workspace_config

    if hasattr(core, "app"):
        from .host_bridge import install_cli

        install_cli(core.app)

    core._MULTI_AGENT_ADAPTERS_INSTALLED = True
